### ISSUE TITLE
[REQUEST] Social icons

### ISSUE THREAD

**Issue by dotnetCarpenter** [PolymerLabs/polyicon#2]
This is a great service but it's missing social icons, which pretty much is a requirement for all the sites I create.
Right now, twitter and reddit is missing before I can use the icon-set. I'll have to go to [IcoMoon](https://icomoon.io/) and wrap that in a component.

**Comment by ebidel** [comment]
Polymer's icon set is generated from the material design iconset. I would make this request over there: https://github.com/google/material-design-icons

**Comment by dotnetCarpenter** [comment]
Would be good to mention in the [README](../#readme)

**Comment by dotnetCarpenter** [comment]
@ebidel can you point to the code that generates `iron-icon` from an icon set? I'm interested in generating my own polymer web component icon set. I need to facilitate non programmers, doing web design and are building an UI library in polymer. So far they are on-board with doing HTML which is enough to create pages using web components.
